### ISSUE TITLE
Use opencv-headless

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/scikit-surgerycalibration#43]
If we can use opencv headless we can help avoid qt conflicts downstream. Currently the apps in the ui folder use opencv GUI windows. If we can move or modify them then we can change the opencv requirement.

**Comment by thompson318** [comment]
PySide doesn't get pulled in by anything else, so if we're going to keep these apps we need some kind of GUI, which makes it tricky.

**Comment by MattClarkson** [comment]
Have we gone down the right route here? 

You should only ever have one of opencv-python, opencv-contrib-python and opencv-contrib-python-headless. I can see how we can use opencv-contrib-python-headless, and then build GUIs using PySide2 as a separate dependency. But what about imshow windows? Does that use a Qt window? or some other type of window. If it uses a Qt window, and then is not present in opencv-contrib-python-headless, we are essentially saying we cannot use imshow. Or we have to revert to opencv-contrib-python.

**Comment by thompson318** [comment]
opencv-contrib-python pulls in it's own version of qtbinaries. So if we have opencv-contrib-python and pyside we end up with two qtbinaries which will at some point lead to a conflict and unpredictable behaviour. My preferred strategy would to be not use imshow anywhere. So opencv for CV and qt for GUI.
